# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    category:
        label: 分类
        modelClass: Vox\Video\Models\Category
        conditions: category_id in (:filtered)
        nameFrom: title
    created_at:
        label: 创建于
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'
    updated_at:
        label: 修改于
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
